[metadata]
name = zpaq
version = 0.3.2
author = zh
author_email = imnotgivingmyemailjustaddmeondiscordmydiscordisz_h_@zh.com
description = Pure in-memory ZPAQ compression for Python (real pybind11 bindings, prebuilt wheels, no C++ toolchain needed to install).
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/zen-ham/zpaq
project_urls =
    Bug Tracker = https://github.com/zen-ham/zpaq/issues
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: C++
    License :: Public Domain
    Operating System :: Microsoft :: Windows
    Operating System :: POSIX :: Linux
    Operating System :: MacOS
    Topic :: System :: Archiving :: Compression

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8
include_package_data = True
zip_safe = False

[options.packages.find]
where = src
